services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_IMAGE_TAG}
    ports:
      - "${PROMETHEUS_HOST_PORT}:9090"
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--config.file=/home/prometheus.yml'
      - '--web.enable-lifecycle'
    restart: always
    volumes:
      # make sure gpu-metrics-prometheus-config.yaml has 777
      # sudo chmod -R 777 gpu-metrics-prometheus-config.yaml
      - ./gpu-metrics-prometheus-config.yaml:/home/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gpu_metrics

  grafana:
    image: grafana/grafana:${GRAFANA_IMAGE_TAG}
    ports:
      - "${GRAFANA_HOST_PORT}:3000"
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana_provisioning:/etc/grafana/provisioning:ro
      - ./grafana_dashboards:/etc/dashboards:ro
    networks:
      - gpu_metrics

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  gpu_metrics:
    driver: bridge
